name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release/NUEL.zip . -x ".git/*" ".github/*" "release/*"
    - name: Release to Github
      run: |
      git add *
      git commit -m "Created ZIP file"
      git push